name: publish npm package

on:
  push:
    paths:
      - "package.json"
    branches:
      - main

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/
          scope: "@400f"
      - name: can npm publish
        id: can
        run: |
          set -eu
          npm i -g can-npm-publish
          if can-npm-publish; then
            echo "##[set-output name=result;]true"
          else
            echo "##[set-output name=result;]false"
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: npm install
        run: |
          set -eu
          npm install
      - name: test
        run: |
          set -eu
          npm run test
      # キャッシュ機構なくてワロタ
      # TODO: feature増えたらちゃんとやる
      - name: publish
        if: steps.can.outputs.result == 'true'
        run: |
          set -eu
          echo "//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}" >> ~/.npmrc
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
